### PR TITLE
Complete pattern in case in runNet'

### PR DESCRIPTION
**Pull request by LambdaP**
Implement the case for SCons in the first argument of runNet', which led to netTest not working properly.

### CODE REVIEW

**Comment by mstksg** [comment]
Thanks!  I actually never even realized that the source for `runNet'` wasn't on the blog post, either.  Thank you for the catch and the fix.

**Comment by LambdaP** [comment]
Pleasure. You may want to check the solution to hiddenSing as well. The solution hasn’t been updated and I wasn’t able to write one that typechecks.

Great tutorial, by the way. I’m really looking forward to integrating dependent types in my Haskell code.

**Comment by mstksg** [comment]
Ah, I see what happened.  The post was in the middle of a re-write that never finished, but I accidentally pushed the in-progress changes online.  I'll fix this asap.

**Comment by mstksg** [comment]
Alright, should be all working now.  That's what I get for making my tutorial code the same as my testing code v.v

**Pull request merged**
