### PR TITLE
Stack should use the singletons library

### PR DESCRIPTION
**Pull request by ivan-m**
Since you're no longer using typelits-witnesses

### CODE REVIEW

**Comment by ivan-m** [comment]
Actually, this ended up being insufficient to be able to treat this as a script:
- Also needs the `LambdaCase` pragma
- There seem to be more functions (such as `randomVector`) and types (such as `Uniform`) that it can't find

**Comment by mstksg** [comment]
Hm, the hmatrix functionality should work if you use the `stack.yaml` in the blog post; the issue is that the latest hmatrix version isn't up on hackage yet :'(

I might want to take out the script form completely though because it probably isn't a good idea to run it unoptimized anyway, heh.  Thanks for bringing this to my attention!

**Comment by ivan-m** [comment]
Yeah, I just tried using the script form of this (if nothing else because I wanted to see how well it worked); looks like it's not really worth it :p

I think the `LambdaCase` pragma addition is still needed though.

I'm going to close this PR though; as if you're going to remove the script part then there's no point in having this ;-)

**Comment by mstksg** [comment]
Yeah, when hmatrix gets updated it'll definitely be a prettier story, unfortunately :'(  but thanks for the heads up, I'll make sure I'll add LambdaCase.

**Pull request closed without merging**
